# Generated by Django 3.2.6 on 2021-11-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0002_auto_20211116_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
