# Generated by Django 3.2.6 on 2021-11-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211120_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='purchace_price',
            new_name='purchase_price',
        ),
    ]
